-- Supabase Table Creation Query
-- Run this in your Supabase project's SQL Editor (https://supabase.com/dashboard/project/_/sql)

create table songs (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text default 'Unknown Artist',
  audio_url text not null,
  created_at timestamp with time zone default now()
);

-- Enable Row Level Security (RLS)
alter table songs enable row level security;

-- Policy to allow public read access (SELECT)
create policy "Allow public read access on songs"
  on songs for select
  using (true);

-- Policy to allow public insert access (INSERT)
create policy "Allow public insert access on songs"
  on songs for insert
  with check (true);

-- Enable Realtime for the songs table
alter publication supabase_realtime add table songs;
